name: deploy_docs 

on:
  # We could deploy docs on every push.
  # push:
  #   branches:
  #     - master 
  #     - main
  # But we only deploy with a release.
  release:
    types: [published]

  # To enable to manually trigger this action.
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: "1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Hatch
        uses: pypa/hatch@a3c83ab3d481fbc2dc91dd0088628817488dd1d5

      - name: Publish on github.io
        run: hatch run docs:ci-build